### ISSUE TITLE
Safari 9.0.1

### ISSUE THREAD

**Issue by MagerValp** [MagerValp/AutoDMGUpdateProfiles#25]
@scifiman https://github.com/MagerValp/AutoDMG/issues/130

I'm getting an error for the Safari 9.0.1 Yosemite update.
The download fails the SHA1 checksum expectation. AutoDMG expected:
8a15d48c94d7b04f89cb3b3faff0dfcc8f7c1859
but got:
abad1886301a442e850b3bf203007b08a7bff5e2

This is happening on a 10.10.5 VM. I've also had issues with this update on my 10.10.5 desktop where it will not install from the AppStore. So I wonder if something has changed with this file from Apple.

**Comment by MagerValp** [comment]
@scifiman this is what I get when I check now:

SafariYo
    name: Safari 9.0.1 for Yosemite
    url: http://swcdn.apple.com/content/downloads/41/44/031-34808/tvl6cc1s49tnt817tyrgsr40dlm4i3cvev/Safari9.0.1Yosemite.pkg
    sha1: 8a15d48c94d7b04f89cb3b3faff0dfcc8f7c1859
    size: 85405995

If you download the update manually, what does `pkgutil --check-signature` and `shasum` say?

**Comment by scifiman** [comment]
When I download from that link, I get the SHA1 sum of abad.
I found out we do have a caching server on our campus so I am probably pulling from it instead of directly from Apple.
Let me check from a hotspot outside our network.

**Comment by scifiman** [comment]
Ok.  So the file direct from Apple seems to be correct.  Guess there is a problem with our caching server and/or network.

Question though, where are the SHA1 keys published now?  I tried to find the Apple document that had the key for this update and couldn't find it through any searches.

**Comment by MagerValp** [comment]
They're not published afaik, I'm grabbing them from software update and calculating the hashes.
