### ISSUE TITLE
Safari 9.1.3 package has invalid URL

### ISSUE THREAD

**Issue by Demoboy** [MagerValp/AutoDMGUpdateProfiles#44]
Currently the URL for the Safari 9.1.3 update for Mavericks errors with 404

**Comment by arubdesu** [comment]
Yeah, that is the deprecated one, try http://swcdn.apple.com/content/downloads/47/05/031-75479/smgdhqybff3jofycbq8uuciu5td7co45am/Safari9.1.3Mavericks.pkg
