### ISSUE TITLE
autodmg-rss.py no longer works

### ISSUE THREAD

**Issue by kevinmcox** [MagerValp/AutoDMGUpdateProfiles#69]
It appears the feed that `autodmg-rss.py` depends on is no longer published by Apple:

FEED_URL = "http://rss.support.apple.com/?channel=DOWNLOADS"

I haven't been able to find an alternative, so `README.md` will need to be updated if an new feed URL isn't available and the suggested workflow has changed.

**Comment by MagerValp** [comment]
Updated the readme for now.

**Comment by kevinmcox** [comment]
Closing this out since there likely won't be a replacement for the feed from Apple.
