### ISSUE TITLE
Update UpdateProfiles.plist with 2018-003 High Sierra

### ISSUE THREAD

**Issue by rocketnova** [MagerValp/AutoDMGUpdateProfiles#71]
Looks like 2018-003 High Sierra just dropped today and is not yet included in the AutoDMG UpdateProfiles.plist: https://support.apple.com/kb/DL1984?locale=en_US

**Comment by kevinmcox** [comment]
It'll need to be added, along with the Safari update. I _might_ have time tomorrow if nobody else does.

**Comment by MagerValp** [comment]
I added Safari 12.0.2 and 10.14.2 today, but I haven't had a chance to test the security updates.

**Comment by kevinmcox** [comment]
I just added it with this PR: #74
